server:
  # http代理端口
  http_host: 0.0.0.0
  http_port: 8080
  # ws 代理端口
  ws_host: 0.0.0.0
  ws_port: 8081
  # client通讯端口
  ws_server_host: 0.0.0.0
  ws_server_port: 8082
  ws_server_authorization: d3VxaWFueXlkcw==
  # web展示端口
  web_host: 0.0.0.0
  web_port: 8083

client:
  # 客户端地址
  server_host: 0.0.0.0
  server_port: 8082
  server_authorization: d3VxaWFueXlkcw==
