FROM golang:alpine AS builder
LABEL org.opencontainers.image.source="https://github.com/thriving123/asyncProxyServer"
LABEL MAINTAINER="ruoli rtsmile"
WORKDIR /

COPY go.mod go.sum ./
RUN go mod download
RUN go mod verify

COPY . .
RUN go build -ldflags="-w -s" -o client ./cmd/client

FROM scratch as runner
WORKDIR /
COPY --from=builder /client COPY --from=builder /server ./app ./ ./
CMD [ "./client" ]
